export default {
  rules: {
    // 基本的なルール
    // 無効な16進数カラーコードを禁止する
    'color-no-invalid-hex': true,
    // フォントファミリー名の重複を禁止する
    'font-family-no-duplicate-names': true,
    // フォントファミリーリストに汎用フォントファミリーキーワードが欠けていることを禁止する
    'font-family-no-missing-generic-family-keyword': true,
    // calc関数内の演算子の前後にスペースがない場合を禁止する
    'function-calc-no-unspaced-operator': true,
    // linear-gradient関数で非標準の方向構文を禁止する
    'function-linear-gradient-no-nonstandard-direction': true,
    // 文字列内の（エスケープされていない）改行を禁止する
    'string-no-newline': true,
    // 不明な単位を禁止する
    'unit-no-unknown': true,
    // 不明なプロパティを禁止する
    'property-no-unknown': true,
    // 宣言ブロック内のプロパティの重複を禁止する
    'declaration-block-no-duplicate-properties': true,
    // ショートハンドプロパティが同じブロック内の他のロングハンドプロパティを上書きすることを禁止する
    'declaration-block-no-shorthand-property-overrides': true,
    // 空のブロックを禁止する
    'block-no-empty': true,
    // 不明な疑似クラスセレクタを禁止する
    'selector-pseudo-class-no-unknown': true,
    // 不明な疑似要素セレクタを禁止する
    'selector-pseudo-element-no-unknown': true,
    // 不明なタイプセレクタを禁止する
    'selector-type-no-unknown': true,
    // 不明なメディア機能名を禁止する
    'media-feature-name-no-unknown': true,
    // 空のコメントを禁止する
    'comment-no-empty': true,
    // セレクタの重複を禁止する
    'no-duplicate-selectors': true,
    // 空のソースを禁止する
    'no-empty-source': true,
    // CSSで無効な二重スラッシュコメントを禁止する
    'no-invalid-double-slash-comments': true,
    // 不明なアニメーション名を禁止する
    'no-unknown-animations': true,
  },
}
