name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  NEXT_PUBLIC_FIREBASE_API_KEY: your-api-key
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: your-project-id.firebaseapp.com
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: your-project-id
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: your-project-id.appspot.com
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: your-messaging-sender-id
  NEXT_PUBLIC_FIREBASE_APP_ID: demo-your-app-id
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: your-measurement-id
  NEXT_PUBLIC_GITHUB_APP_NAME: github-app-name

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run linters
        run: bun run lint

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run tests
        env:
          GITHUB_APP_ID: ${{ secrets.CI_GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.CI_GITHUB_APP_PRIVATE_KEY }}
          GITHUB_APP_CLIENT_ID: ${{ secrets.CI_GITHUB_APP_CLIENT_ID }}
          GITHUB_APP_CLIENT_SECRET: ${{ secrets.CI_GITHUB_APP_CLIENT_SECRET }}
          XAMAN_API_KEY: ${{ secrets.XAMAN_API_KEY }}
          XAMAN_API_SECRET: ${{ secrets.XAMAN_API_SECRET }}
        run: bun test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        env:
          GITHUB_APP_ID: ${{ secrets.CI_GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.CI_GITHUB_APP_PRIVATE_KEY }}
          GITHUB_APP_CLIENT_ID: ${{ secrets.CI_GITHUB_APP_CLIENT_ID }}
          GITHUB_APP_CLIENT_SECRET: ${{ secrets.CI_GITHUB_APP_CLIENT_SECRET }}
          XAMAN_API_KEY: ${{ secrets.XAMAN_API_KEY }}
          XAMAN_API_SECRET: ${{ secrets.XAMAN_API_SECRET }}
        run: bun install
      - name: Build
        run: bun run build

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Run Playwright tests
        env:
          GITHUB_APP_ID: ${{ secrets.CI_GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.CI_GITHUB_APP_PRIVATE_KEY }}
          GITHUB_APP_CLIENT_ID: ${{ secrets.CI_GITHUB_APP_CLIENT_ID }}
          GITHUB_APP_CLIENT_SECRET: ${{ secrets.CI_GITHUB_APP_CLIENT_SECRET }}
          XAMAN_API_KEY: ${{ secrets.XAMAN_API_KEY }}
          XAMAN_API_SECRET: ${{ secrets.XAMAN_API_SECRET }}
        run: bun run e2e-test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
