name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  NEXT_PUBLIC_FIREBASE_API_KEY: your-api-key
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: your-project-id.firebaseapp.com
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: your-project-id
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: your-project-id.appspot.com
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: your-messaging-sender-id
  NEXT_PUBLIC_FIREBASE_APP_ID: demo-your-app-id
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: your-measurement-id
  NEXT_PUBLIC_GITHUB_APP_NAME: github-app-name

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run linters
        run: bun run lint

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run tests
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          GITHUB_APP_ID: ${{ secrets.CI_GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.CI_GITHUB_APP_PRIVATE_KEY }}
          GITHUB_APP_CLIENT_ID: ${{ secrets.CI_GITHUB_APP_CLIENT_ID }}
          GITHUB_APP_CLIENT_SECRET: ${{ secrets.CI_GITHUB_APP_CLIENT_SECRET }}
          XUMM_API_KEY: ${{ secrets.XUMM_API_KEY }}
          XUMM_API_SECRET: ${{ secrets.XUMM_API_SECRET }}
          XRPL_NETWORK: ${{ secrets.XRPL_NETWORK }}
          XRPL_ISSUER_1_ADDRESS: ${{ secrets.XRPL_ISSUER_1_ADDRESS }}
          XRPL_ISSUER_1_SECRET: ${{ secrets.XRPL_ISSUER_1_SECRET }}
          XRPL_ISSUER_1_ACTIVE: ${{ secrets.XRPL_ISSUER_1_ACTIVE }}
          XRPL_TREASURY_1_ADDRESS: ${{ secrets.XRPL_TREASURY_1_ADDRESS }}
          XRPL_TREASURY_1_SECRET: ${{ secrets.XRPL_TREASURY_1_SECRET }}
          XRPL_TREASURY_1_ACTIVE: ${{ secrets.XRPL_TREASURY_1_ACTIVE }}
          TX_VERIFICATION_HASH_SALT: ${{ secrets.TX_VERIFICATION_HASH_SALT }}
        run: bun run test

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          GITHUB_APP_ID: ${{ secrets.CI_GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.CI_GITHUB_APP_PRIVATE_KEY }}
          GITHUB_APP_CLIENT_ID: ${{ secrets.CI_GITHUB_APP_CLIENT_ID }}
          GITHUB_APP_CLIENT_SECRET: ${{ secrets.CI_GITHUB_APP_CLIENT_SECRET }}
          XUMM_API_KEY: ${{ secrets.XUMM_API_KEY }}
          XUMM_API_SECRET: ${{ secrets.XUMM_API_SECRET }}
          XRPL_NETWORK: ${{ secrets.XRPL_NETWORK }}
          XRPL_ISSUER_1_ADDRESS: ${{ secrets.XRPL_ISSUER_1_ADDRESS }}
          XRPL_ISSUER_1_SECRET: ${{ secrets.XRPL_ISSUER_1_SECRET }}
          XRPL_ISSUER_1_ACTIVE: ${{ secrets.XRPL_ISSUER_1_ACTIVE }}
          XRPL_TREASURY_1_ADDRESS: ${{ secrets.XRPL_TREASURY_1_ADDRESS }}
          XRPL_TREASURY_1_SECRET: ${{ secrets.XRPL_TREASURY_1_SECRET }}
          XRPL_TREASURY_1_ACTIVE: ${{ secrets.XRPL_TREASURY_1_ACTIVE }}
          TX_VERIFICATION_HASH_SALT: ${{ secrets.TX_VERIFICATION_HASH_SALT }}
        run: bun run build
